# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles(paths) }}
      - name: Run the build process with imbuilder docker
        uses: addnab/docker-run-action@v3
        with:
          image: mvesanen/imbuilder:latest
          options: -v ${{ github.workspace }}:/git
          run: /docbuild/default-build.sh /git/markdown/main.md
      - name: collect pdf artefat 
        uses: actions/upload-artifact@v3
        with:
          name: Inframodel (PDF)
          path: ${{ github.workspace }}/artefact/Inframodel_DRAFT.pdf
      - name: collect md artefact
        uses: actions/upload-artifact@v3
        with:
          name: Inframodel (md)
          path: ${{ github.workspace }}/artefact/inframodel.md
      
